language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t marcosjampietri/docker-react -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true marcosjampietri/docker-react npm test

after_success:
    - docker build -t marcosjampietri/multi-client ./client
    - docker build -t marcosjampietri/multi-nginx ./nginx
    - docker build -t marcosjampietri/multi-server ./server

    - echo "$DOCKER_ID" | docker login -u "$DOCKER_PASSWORD" --password-stdin

    - docker push marcosjampietri/multi-client
    - docker push marcosjampietri/multi-nginx
    - docker push marcosjampietri/multi-server

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-923445559289"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
