version: "3"
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "5150:80"
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        links:
            - mongo
        ports:
            - "5000:5000"
        environment:
            DATABASE: "mongodb+srv://soundtoart:fUO5C1UtdOCtW4Sm@butterflycluster.und5c.mongodb.net/MarcosDB?retryWrites=true&w=majority"
            PORT: "5000"
    mongo:
        image: "mongo"
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - marcos-db:/data/db
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        links:
            - mongo
volumes: marcos-db:
